"""delivery_log lifecycle_stage 추가

Revision ID: 0296f3cc303a
Revises: d3b4eca9ad24
Create Date: 2026-07-05 19:05:51.256684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0296f3cc303a'
down_revision: Union[str, None] = 'd3b4eca9ad24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_log', sa.Column('lifecycle_stage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_log', 'lifecycle_stage')
    # ### end Alembic commands ###
